# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM&RAC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MVVM&RAC
pod 'AFNetworking', '~> 3.0’
pod 'ReactiveCocoa', '~> 2.5'
end
